### ISSUE TITLE
potential typo in the notebook for "Fine-tune Falcon 180B with QLoRA and Flash Attention on Amazon SageMaker"

### ISSUE THREAD

**Issue by insop** [philschmid/sagemaker-falcon-180b-samples#2]
Thank you for good articles.

In this [article)[https://www.philschmid.de/sagemaker-falcon-180b-qlora) which uses dolly dataset, I found the following text.
I want to mention this to you to review in case.

- [code](https://github.com/philschmid/sagemaker-falcon-180b-samples/blob/master/training/sagemaker-notebook.ipynb)

```
To load the samsum dataset, we use the load_dataset() method from the 🤗 Datasets library.
```

**Comment by philschmid** [comment]
Thanks for letting me know
